### PR TITLE
no need to cache momentum if nesterov is disabled

### PR DESCRIPTION
**Pull request by ethansmith2000**
no need to cache momentum if nesterov is disabled, also g.add can be done in place

### CODE REVIEW

**Comment by KellerJordan** [comment]
not-inplace is how it's done in the official torch SGD, so it's good enough for me. not sure why disabling nesterov would mean you don't need momentum.

**Comment by ethansmith2000** [comment]
ok I see, if nesterov is disabled though momentum isn't used anywhere

Screenshot 2024-11-28 at 1 34 58 PM

**Comment by KellerJordan** [comment]
oh, good point. that's a bug

**Comment by KellerJordan** [comment]
fixed, thanks!

**Pull request closed without merging**
